name: Run tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress
          wget https://github.com//typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz
          tar -xvf typst-x86_64-unknown-linux-musl.tar.xz --strip-components=1 typst-x86_64-unknown-linux-musl/typst
          sudo chmod +x ./typst
          sudo mv ./typst /usr/bin/typst

      - name: Run test suite
        run: composer run-script test